### ISSUE TITLE
I think I broke the app dev :D 

### ISSUE THREAD

**Issue by alexandrosk** [carstenlebek/shopify-node-app-starter#12]
Hello! Thanks for the awesome work, in case you know what's up, I tried to add cli3 inside the app and then I completely destroyed it.

When running the npm run dev I get , `Variable $applicationUrl of type Url! was provided invalid value: {"response":{"errors":[{"message":"Variable $applicationUrl of type Url! was provided` 

Its around this line 
`ShopifyCli.mjs file `
`const result = await api.partners.request(query, token, variables);` 

Although all the strings are looking ok it expects a type of URL 

I removed everything and the folders, cloned again etc, I installed everything again with force and npm audit fix but no luck.
Let me know if you have any idea! Thanks

**Comment by alexandrosk** [comment]
I believe it's something with me trying to install shopify-cli globally or something like this, I uninstalled it from anywhere but still the same :/

**Comment by msmps** [comment]
I came across this a couple of days ago...

It looks like something possibly changed upstream in the cli-kit and the lack of `package-lock.json` means we're pulling in the updated version.

You need to change the below lines in `shopifyCli.mjs`

```typescript
const variables = {
	apiKey,
	appUrl: url,
	redir: [
		`${url}/api/auth`,
		`${url}/api/auth/callback`,
		`${url}/api/auth/offline`,
		`${url}/api/auth/offline-callback`,
		`${url}/api/auth/toplevel`,
	],
};
```

## Solution:

```typescript
const variables = {
	apiKey,
	applicationUrl: url,
	redirectUrlWhitelist: [
		`${url}/api/auth`,
		`${url}/api/auth/callback`,
		`${url}/api/auth/offline`,
		`${url}/api/auth/offline-callback`,
		`${url}/api/auth/toplevel`,
	],
};
```

**Comment by alexandrosk** [comment]
Solved thanks a ton!
