### ISSUE TITLE
Perform fewer HTTP calls at the Callback Endpoint (Solution)

### ISSUE THREAD

**Issue by aimproxy** [carstenlebek/shopify-node-app-starter#15]
I've been playing around with Shopify OAuth a little bit again and I might discover a way of not doing too many requests into the callback endpoints.

I realised if I tweak a little bit the code of the session storage file, at the callback endpoint we would have to persist a second time the shop into Redis!

There are only two cases during Shopify OAuth that need to be handled! We know that Shopify uses `session.id` from the `SessionInterface`, the ID can vary between a `uuidv4 string` and the shop URL with a suffixed number like this: `.myshopify.com_123456789`.

Suffice to say, that we only need to handle the `storeCallback` and the `loadCallback` to make this work, let's see some code:
```js

const SHOPIFY_DOMAIN = ".myshopify.com";

const storeCallback = async (session: SessionInterface): Promise<boolean> => {
  const result = await redis.set(
    session.id.includes(SHOPIFY_DOMAIN) ? session.shop : session.id,
    JSON.stringify(session),
    session.id.includes("offline") ? {} : { ex: 36000 }
  );

  return result === "OK";
};

const getShopDomainIfPresent = (shopId: string): string | null => {
  if (shopId.includes(SHOPIFY_DOMAIN)) {
    return shopId.substring(0, shopId.indexOf("_"));
  }

  return null;
};

const loadCallback = async (shopId: string): Promise<SessionInterface | { [key: string]: unknown } | undefined> => {
  const result = await redis.get<Promise<SessionInterface | null>>(getShopDomainIfPresent(shopId) || shopId);

  return result ?? undefined;
};

const deleteCallback = async (shopId: string): Promise<boolean> => {
  const result = await redis.del(getShopDomainIfPresent(shopId) || shopId);

  return result > 0;
};
```

By doing this, this piece of code is now obsolete benefiting from fewer calls at the callback endpoint!
```js
      const redis = new Redis({
        url: process.env.UPSTASH_REDIS_REST_URL as string,
        token: process.env.UPSTASH_REDIS_REST_TOKEN as string
      });

      const redisShop = await redis.get(session.shop);
      if (!redisShop || redisShop !== process.env.SCOPES) {
        await redis.set(session.shop, session);
      }
```

**Comment by aimproxy** [comment]
@carstenlebek I'm willing to make a PR if you agree with this approach!

**Comment by carstenlebek** [comment]
Hey, sorry for the late response. I understand, what you are trying to archive, but the code you want to remove isn't really related to the session storage. It is meant to check, if the app has been installed on the shop. There will be issues, when you uninstall and reinstall the app, if this is removed.

The reasoning behind this is to create a step in the auth callback, where you for example can create your db records in your own backend. I've also implemented a check to make sure the app has the right access scopes for the admin API.
