### ISSUE TITLE
Abort [Error]: The CLIKitStore instance hasn't been initialized & AppBridgeError: APP::ERROR::INVALID_CONFIG: host must be provided

### ISSUE THREAD

**Issue by testuser4334** [carstenlebek/shopify-node-app-starter#4]
Hey guys.
Unfortunately, it is not possible to set up the project due to two errors. Been trying to get the project to run for hours.

Error 1: Abort [Error]: The CLIKitStore instance hasn't been initialized - The CLIKitStore instance hasn't been initialized in line 35 @ next.config.mjs before `session.ensureAuthenticatedPartners();` is called. I couldn't find any documentation on @shopify/cli-kit and trying `await store.initializeCliKitStore();` in line 34 doesn't seem to work either. How do I initialize the store before the session is authenticated?

Error 2: AppBridgeError: APP::ERROR::INVALID_CONFIG: host must be provided - Whether I comment out the host in line 62 @ next.config.mjs or not, the host seems to be non-resolvable. Do I need to define an additional host in the dotenv? `HOST=https://localhost` does not seem to work for me, even tho I set it as URL in the Shopify Plugin. Is there a solution for this?

I would be very grateful for any solutions and advice and thank you in advance.

Have a nice evening everyone :)

**Comment by carstenlebek** [comment]
Hey, I'm not able to replicate your errors. Which version of Node.js are you using?

**Comment by testuser4334** [comment]
> Hey, I'm not able to replicate your errors. Which version of Node.js are you using?
Hey. I tested both 16.19.0 & 14.17.6, resulted in the same error (The CLIKitStore instance hasn't been initialized...).

However, it seems like the hosted versions on Vercel have the same issues.
https://typescript-next-shopify-app-git-main-konzeptfabrik.vercel.app/
![Image](https://i.imgur.com/WQRzXsQ.png)

I'm still trying to get it to work and appreciate any ideas :)

**Comment by testuser4334** [comment]
Oops, was not planned to close the issue.

**Comment by aimproxy** [comment]
Hey, @testuser4334 I did have the same problem but with a slithy different error code but the message `host must be provided` was there! I managed to get rid of the error by passing as query parameters the host in every single authentication URL! Not sure if it is the current implementation, I will need to read further the Shopify docs on this... But perhaps @carstenlebek can clarify us on that matter? Basically they look like this: `?shop=${req.query.shop}&host=${req.query.host}`

**Comment by carstenlebek** [comment]
There were some issues in the middleware and auth api routes. I've changed a few things and tested it, all should be working as expected now. You can see the changes in the lates [commit](https://github.com/carstenlebek/shopify-node-app-starter/commit/41c938194b22fea233210dee6da54930228d0fc0#diff-0626369278c89781505d2c04865ecce1302e979271bcfb471e029c19addc13a0).

Please let me know, If there are more issues!

**Comment by aimproxy** [comment]
Yup, that fixed the issue!
