### ISSUE TITLE
CustomProperties deprecated + Hydration failure

### ISSUE THREAD

**Issue by aimproxy** [carstenlebek/shopify-node-app-starter#5]
Deprecation: The `CustomProperties` component has been deprecated. See the v10 migration guide for replacing dark color scheme styles. https://github.com/Shopify/polaris/blob/main/documentation/guides/migrating-from-v9-to-v10.md

Error: Hydration failed because the initial UI does not match what was rendered on the server.
See more info here: https://nextjs.org/docs/messages/react-hydration-error

How do I fix this?

**Comment by carstenlebek** [comment]
There's nothing to fix. It's an early deprecation message in V9, like mentioned in [this issue.](https://github.com/Shopify/polaris/issues/6504)

Where and when are you getting the hydration error?

**Comment by aimproxy** [comment]
@carstenlebek is there a way to silence the warning?

![Screenshot 2022-07-20 at 10-31-37 Mineshop Development Store · mineshop · Shopify](https://user-images.githubusercontent.com/47716563/179949248-7b7f8c1b-6357-4d62-8e28-3a23f38dd3d3.png)

**Comment by carstenlebek** [comment]
I don't know, if there is a way to suppress this error, but you should rather find the reason for the error.
