### ISSUE TITLE
return-top-level-redirection.ts:15 points to clebek shop.

### ISSUE THREAD

**Issue by hfoffani** [carstenlebek/shopify-node-app-starter#6]
Hi,
The helper returnToLevelRedirection function (line 15) points to `${process.env.HOST}/api/auth?shop=clebek.myshopify.com`.
Should it be redirectUrl instead?

Thanks!!!

**Comment by carstenlebek** [comment]
Thanks for noticing! Yes, it should be redirectUrl. I've fixed it.
