### ISSUE TITLE
Cookies gone after app is embedded (without offline endpoints)

### ISSUE THREAD

**Issue by aimproxy** [carstenlebek/shopify-node-app-starter#9]
I removed the offline access tokens endpoint as my app won't need to contact Shopify API without the user consentiment.

So my middleware ends up like this:
```ts
    const urlParams = new URLSearchParams(req.url?.split('?')[1]);
    const {shop} = Object.fromEntries(urlParams);

    if (
        req.nextUrl.pathname.startsWith('/api/auth') ||
        req.nextUrl.pathname.startsWith('/api/webhooks')
    ) {
        return NextResponse.next();
    }

    if (req.nextUrl.pathname.startsWith('/api')) {
        return await withShopifyMiddleware(req, shop);
    }

    if (shop) {
        const shopSession = await findShopByShopDomain(shop)
        console.info(shopSession)

        if (!shopSession) {
            return NextResponse.redirect(
                `${process.env.HOST}/api/auth/?shop=${shop}`
            );
        }

        return NextResponse.next({
            headers: {
                'Content-Security-Policy': `frame-ancestors https://${shop} https://admin.shopify.com;`,
            },
        });
    }

    return NextResponse.next();
```
I also changed a few things here and there and now Cookies are gone after the app rich is embedded state and
 ```ts
    const bearerPresent = req.headers.get('authorization')?.match(/Bearer (.*)/);
```
is always undefined!

@carstenlebek Any thoughts on why this might append?

**Comment by carstenlebek** [comment]
There is an environment variable to deactivate offline sessions in production and I would recommend you to use it. The offline session token is required to get the schema of the Shopify GraphQL API.

As I have no way of knowing, what exactly you have changed, I can't really help you here. The authorization header has nothing to do with cookies. It is set by appBridge with authenticatedFetch in the useAuthenticatedFetch hook.

**Comment by aimproxy** [comment]
I will take a look again at why cookies disappear maybe I missed something! I knew that offline tokens are required to fetch the GraphQL Schema! The weird thing is that it was working like a charm until I tweaked just a few things.

Do you mind confirming that the middleware lets you in without an online session token if the shop is present at Redis? In that case, auth is called when the shop is not present or verifyRequest is called?
